var createDecryptor=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var moduleRtn;var c=moduleArg,aa=!!globalThis.window,r=!!globalThis.WorkerGlobalScope,t=globalThis.process?.versions?.node&&globalThis.process?.type!="renderer",u=(a,b)=>{throw b;};typeof __filename!="undefined"?_scriptName=__filename:r&&(_scriptName=self.location.href);var v="",w,x;
if(t){var fs=require("node:fs");v=__dirname+"/";x=a=>{a=y(a)?new URL(a):a;return fs.readFileSync(a)};w=async a=>{a=y(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.slice(2);u=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||r){try{v=(new URL(".",_scriptName)).href}catch{}r&&(x=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});w=async a=>{if(y(a))return new Promise((d,e)=>{var f=new XMLHttpRequest;f.open("GET",
a,!0);f.responseType="arraybuffer";f.onload=()=>{f.status==200||f.status==0&&f.response?d(f.response):e(f.status)};f.onerror=e;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var z=console.error.bind(console),A,B=!1,C,y=a=>a.startsWith("file://"),F,G,H=!1;
function I(){var a=J.buffer;K=new Int8Array(a);new Int16Array(a);c.HEAPU8=L=new Uint8Array(a);new Uint16Array(a);new Int32Array(a);new Uint32Array(a);new Float32Array(a);new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}function M(a){c.onAbort?.(a);a=`Aborted(${a})`;z(a);B=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");G?.(a);throw a;}var N;
async function ba(a){if(!A)try{var b=await w(a);return new Uint8Array(b)}catch{}if(a==N&&A)a=new Uint8Array(A);else if(x)a=x(a);else throw"both async and sync fetching of the wasm failed";return a}async function ca(a,b){try{var d=await ba(a);return await WebAssembly.instantiate(d,b)}catch(e){z(`failed to asynchronously prepare wasm: ${e}`),M(e)}}
async function da(a){var b=N;if(!A&&!y(b)&&!t)try{var d=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(d,a)}catch(e){z(`wasm streaming compile failed: ${e}`),z("falling back to ArrayBuffer instantiation")}return ca(b,a)}class O{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var K,L,P=a=>{for(;a.length>0;)a.shift()(c)},Q=[],R=[],ea=()=>{var a=c.preRun.shift();R.push(a)},S=!0,T=0,U={},V=a=>{C=a;S||T>0||(c.onExit?.(a),B=!0);u(a,new O(a))},fa=a=>{if(!B)try{a()}catch(b){b instanceof O||b=="unwind"||u(1,b)}finally{if(!(S||T>0))try{C=a=C,V(a)}catch(b){b instanceof O||b=="unwind"||u(1,b)}}},ha=new TextDecoder,W=(a,b,d)=>{if(a){var e=a,f=L;b=e+b;if(d)d=b;else{for(;f[e]&&!(e>=b);)++e;d=e}a=ha.decode(L.subarray(a,d))}else a="";return a},ka=(a,b,d,e)=>{var f={string:k=>{var m=0;
if(k!==null&&k!==void 0&&k!==0){for(var g=m=0;g<k.length;++g){var h=k.charCodeAt(g);h<=127?m++:h<=2047?m+=2:h>=55296&&h<=57343?(m+=4,++g):m+=3}var p=m+1;g=m=X(p);h=L;if(p>0){p=g+p-1;for(var D=0;D<k.length;++D){var l=k.codePointAt(D);if(l<=127){if(g>=p)break;h[g++]=l}else if(l<=2047){if(g+1>=p)break;h[g++]=192|l>>6;h[g++]=128|l&63}else if(l<=65535){if(g+2>=p)break;h[g++]=224|l>>12;h[g++]=128|l>>6&63;h[g++]=128|l&63}else{if(g+3>=p)break;h[g++]=240|l>>18;h[g++]=128|l>>12&63;h[g++]=128|l>>6&63;h[g++]=
128|l&63;D++}}h[g]=0}}return m},array:k=>{var m=X(k.length);K.set(k,m);return m}};a=c["_"+a];var n=[],E=0;if(e)for(var q=0;q<e.length;q++){var Z=f[d[q]];Z?(E===0&&(E=ia()),n[q]=Z(e[q])):n[q]=e[q]}d=a(...n);return d=function(k){E!==0&&ja(E);return b==="string"?W(k):b==="boolean"?!!k:k}(d)};c.noExitRuntime&&(S=c.noExitRuntime);c.printErr&&(z=c.printErr);c.wasmBinary&&(A=c.wasmBinary);if(c.preInit)for(typeof c.preInit=="function"&&(c.preInit=[c.preInit]);c.preInit.length>0;)c.preInit.shift()();
c.cwrap=(a,b,d,e)=>{var f=!d||d.every(n=>n==="number"||n==="boolean");return b!=="string"&&f&&!e?c["_"+a]:(...n)=>ka(a,b,d,n)};c.UTF8ToString=W;
var la,ja,X,ia,J,ma={d:()=>M(""),c:()=>{S=!1;T=0},a:(a,b)=>{U[a]&&(clearTimeout(U[a].id),delete U[a]);if(!b)return 0;var d=setTimeout(()=>{delete U[a];fa(()=>la(a,performance.now()))},b);U[a]={id:d,u:b};return 0},e:a=>{var b=L.length;a>>>=0;if(a>2147483648)return!1;for(var d=1;d<=4;d*=2){var e=b*(1+.2/d);e=Math.min(e,a+100663296);a:{e=(Math.min(2147483648,Math.ceil(Math.max(a,e)/65536)*65536)-J.buffer.byteLength+65535)/65536|0;try{J.grow(e);I();var f=1;break a}catch(n){}f=void 0}if(f)return!0}return!1},
b:V},Y;Y=await (async function(){function a(d){d=Y=d.exports;c._wasm_alloc=d.h;c._wasm_free=d.i;c._wasm_decrypt=d.j;c._wasm_get_result=d.k;c._wasm_get_result_len=d.l;c._wasm_free_result=d.m;la=d.n;ja=d.o;X=d.p;ia=d.q;J=d.f;I();return Y}var b={a:ma};if(c.instantiateWasm)return new Promise(d=>{c.instantiateWasm(b,(e,f)=>{d(a(e,f))})});N??=c.locateFile?c.locateFile("decrypt.wasm",v):v+"decrypt.wasm";return function(d){return a(d.instance)}(await da(b))}());
(function(){function a(){c.calledRun=!0;if(!B){H=!0;Y.g();F?.(c);c.onRuntimeInitialized?.();if(c.postRun)for(typeof c.postRun=="function"&&(c.postRun=[c.postRun]);c.postRun.length;){var b=c.postRun.shift();Q.push(b)}P(Q)}}if(c.preRun)for(typeof c.preRun=="function"&&(c.preRun=[c.preRun]);c.preRun.length;)ea();P(R);c.setStatus?(c.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>c.setStatus(""),1);a()},1)):a()})();H?moduleRtn=c:moduleRtn=new Promise((a,b)=>{F=a;G=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=createDecryptor;module.exports.default=createDecryptor}else if(typeof define==="function"&&define["amd"])define([],()=>createDecryptor);
