package net.friendly_bets.models.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum BetTitleSubCategory {
    SUMMARY,
    HOME_WIN, DRAW, AWAY_WIN, OTHER_RESULTS,
    GAME_RESULT_TOTAL_UNDER, GAME_RESULT_TOTAL_OVER,
    TOTAL_UNDER, TOTAL_OVER, PERSONAL_TOTAL,
    HANDICAP_HOME, HANDICAP_AWAY,
    SCORE_0_0_TO_3_3, SCORE_OTHER,
    BOTH_SCORES, BOTH_SCORES_AND_GAME_RESULT, BOTH_SCORES_AND_TOTAL_GOALS, OTHER,
    GAME_RESULT, HALF_FULL_FIRST_SECOND, GAME_SCORE, HANDICAP, TOTAL, COMBO_CONDITION, GOALS_HALFTIME,
    CLEAN_WIN, GOALS_DIFFERENCE, PLAYOFF;
}
